---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: librarydb
  name: bookdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librarydb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: librarydb
    spec:
      containers:
      - image: BOOKDB:latest
        imagePullPolicy: IfNotPresent
        name: bookdb
        ports:
        - containerPort: 3306
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: librarydb
  name: librarydb
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: librarydb
  type: ClusterIP
status:
  loadBalancer: {}
